### ISSUE TITLE
Akarunk Rablót? 

### ISSUE THREAD

**Issue by klariann** [klariann/Szofttech-Catan#4]
Ezt az issuet azért indítottuk, hogy alatta beszéljük meg szeretnénk-e rablót vagy nem.

Az **eredeti szabályban** a következő rész vonatkozik rá:

>  Amikor egy játékos 7-est dob, akkor egyik játékos sem jut nyersanyagbevételhez.
> - Minden  olyan játékos, akinél 7 darabnál több nyersanyagkártya van, az a kártyáinak a felét kiválasztja és visszateszi a közös készletbe. Szükség esetén a játékos javára, lefelé kerekítve kell a kártyákat visszaadni. Például 9 nyersanyagkártya birtoklása esetén 4 darabot.
> -  Ezt követően át kell helyezni a rablót (➔): 1. A játékos a rablót egy másik tájmezőre helyezi.
> 2. Ezután a rablót áthelyező játékos elrabol 1 lefordított nyersanyagkártyát az egyik olyan (ha van olyan) játékostársának  a kezéből, akinek települése, vagy városa áll azon a területen, ahová a rablót állította. A megrabolt játékostárs a rablás alatt nyersanyagkártyáit lefordítva tartja a kezében.
> 3. A játékos körét a kereskedési szakasszal folytatja.

Ezzel a baj, hogy akkor bele kell építenünk, hogy a játékos saját maga dönthet az eldobott kártyáiról, illetve a másik játékostól húzást is. (Meg nyilván kell tartani melyik mező nem termel, de ez a legkevesebb mert csak egy logikai változó.)

**Igazából a kérdés az, hogy szeretnénk-e ezt teljesen kivenni belőle, vagy esetleg módosított szabályokkal beletenni.**

**Comment by antalist** [comment]
Én arra szavazok, hogy először csináljuk meg a játékot rabló nélkül. A végén szerintem nem túl nagy pluszmunkával bővíthető rablóval a játék.

**Comment by klariann** [comment]
Hát igazából már a legeslegelején a tervezésnél kell rá gondolni, mert pl. a nem termelő mező jelölésére akkor kell bevezetni valamit...
